<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UserSecretsId>d1ce5608-4584-49a1-8764-7fd7015e2014</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Finmy.Ledger.Application\Finmy.Ledger.Application.csproj" />
  </ItemGroup>

  <ItemGroup Label="Entity Framework Core &amp; Database">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup Label="Configuration">
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup Label="Messaging">
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
  </ItemGroup>

</Project>
